### ISSUE TITLE
Saving out higher bitrate/resolution video files

### ISSUE THREAD

**Issue by dvclmn** [kunikunimitanni/Extract-videos-procreate#1]
Hi kunikunimitanni,

Thanks for creating this very handy tool! I was wondering if there is a way to save out a high(er) resolution / bitrate video? Or perhaps to keep the original procreate canvas dimensions?

It has been so useful to be able to access the time lapse of a procreate file without needing to airdrop the files over to the iPad and back etc. Thanks again, and happy to make a donation to the project if that helps.

Best,

Dave

**Comment by kunikunimitanni** [comment]
HI Dave,

I was surprised and delighted to this tool had a user.

I have done some research on the title issue. To save a high resolution video, set a custom canvas when creating a new one in procreate. I believe that increasing the time lapse settings as much as possible will result in a higher quality file.

This tool will extract the video as it is stored in the Procreate file. If the quality of the resulting video is low, the settings in Procreate may help.

**Comment by kunikunimitanni** [comment]
HI Dave,

I was surprised and delighted to this tool had a user.

This tool will extract the video as it is stored in the Procreate file. If the quality of the resulting video is low, the settings in Procreate may help.

To save a high resolution video, set a custom canvas when creating a new one in procreate. I believe that increasing the time lapse settings as much as possible will result in a higher quality file.

I hope this helps.

**Comment by dvclmn** [comment]
Hello, sorry I missed this reply.

> I was surprised and delighted to this tool had a user.

Yup, your biggest fan over here! Ha

That definitely helps. Yeah I think my issue was just that a particular document I was using had low-res settings, as you mentioned. All the rest have been great.

Thanks again, and all the best!
